# -*- coding: utf-8 -*-
"""Join_flight_and_whether.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7jR6vdBoQ3yUT9DFnUbhGbxrzotXc8k
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd

data = pd.read_csv("flight_data.csv")
planes = pd.read_csv("planes.csv")
airports = pd.read_csv("airports.csv")
carriers = pd.read_csv("carriers.csv")
weather=pd.read_csv("weather.csv")

data.head()

data.dropna()

len(data["tailnum"].unique())

import numpy as np
np.array(data.duplicated(["carrier"])).sum()

weather.drop(labels=["origin","time_hour"],axis=1,inplace=True)

weather.columns

dataset=pd.merge(data,weather,on=["year","day","month","hour"],how='outer').dropna().drop_duplicates(subset=["year","month","day","dep_time","sched_dep_time","dep_delay","arr_time","sched_arr_time","arr_delay","carrier","flight","tailnum","origin","dest"])

dataset.reset_index(inplace=True)

dataset.drop(["index"],axis=1)

dataset.to_csv('dataset.csv',index=False)

planes.head()

dataset.drop("time_hour",axis=1)

